# For more information: https://laravel.com/docs/sail
version: '3'
services:

  backendapi:
    build:
      context: ./Dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: backendapi
    ports:
      - "8000:80"
    volumes:
      - "./:/var/www/html"
    networks:
      - pygesres_net
    # extra_hosts:
    # - 'host.docker.internal:host-gateway'
    depends_on:
      - mysql

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'pygesres-mysql-prod:/var/lib/mysql'
    networks:
      - pygesres_net
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

